version: '3'
services:
  postgre:
    container_name: db_postgre
    restart: always
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "123456"
    volumes:
      - volume:/var/lib/postgresql/data
    ports: 
      - 8080:8080  
volumes:
  volume: