version: '3'
services:
  mssql:
    container_name: db_mssql
    restart: always
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: '123456'
      MSSQL_PID: 'Express'
    volumes:
      - volume:/var/opt/mssql
    ports: 
      - 1433:1433
volumes:
  volume:
